fills_path: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/fills.parquet
# Sequence to load
fill_nb:
- "8496"
# Save results
save_to: /eos/user/a/aradosla/results_nxcals
log_file: ./log.json
parent: ./
