adt_file:
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h24m45s254927us.h5
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h25m43s532446us.h5
bunch_nb_b1:
- 12
- 1971
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8469_2/results_fft_Fill8469_2_027.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor/Fill8469_2/027/tree_maker.log
