adt_file:
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h34m45s513359us.h5
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h35m43s790875us.h5
bunch_nb_b1:
- 12
- 1971
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8469_2/results_fft_Fill8469_2_032.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor/Fill8469_2/032/tree_maker.log
