adt_file:
- ADTObsBox_data/B1H_Q7/4/20/B1H_Q7_20230404_20h15m37s288563us.h5
- ADTObsBox_data/B1H_Q7/4/20/B1H_Q7_20230404_20h16m42s214792us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8524_1/results_fft_Fill8524_1_048.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8524_1/048/tree_maker.log
