adt_file:
- ADTObsBox_data/B1H_Q7/10/17/B1H_Q7_20230410_17h13m27s692532us.h5
- ADTObsBox_data/B1H_Q7/10/17/B1H_Q7_20230410_17h14m25s970054us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8568_1/results_fft_Fill8568_1_056.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8568_1/056/tree_maker.log
