adt_file:
- ADTObsBox_data/B1H_Q7/4/20/B1H_Q7_20230404_20h35m37s808278us.h5
- ADTObsBox_data/B1H_Q7/4/20/B1H_Q7_20230404_20h36m41s913714us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8524_1/results_fft_Fill8524_1_058.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8524_1/058/tree_maker.log
