fills_path: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor_live/fills.parquet
# Sequence to load
fill_nb:
- '8570'
save_to: /eos/user/a/aradosla/SWAN_projects/Analysis/ADTObsBox_analysis/results_nxcals/run_2023
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor_live/ADT_2022_2/068/tree_maker.log
parent: ./
