adt_file:
- ADTObsBox_data/B1H_Q7/30/15/B1H_Q7_20230330_15h25m00s137388us.h5
- ADTObsBox_data/B1H_Q7/30/15/B1H_Q7_20230330_15h26m04s242801us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8510_1/results_fft_Fill8510_1_043.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8510_1/043/tree_maker.log
