adt_file:
- ADTObsBox_data/B1H_Q7/10/19/B1H_Q7_20230410_19h15m27s348981us.h5
- ADTObsBox_data/B1H_Q7/10/19/B1H_Q7_20230410_19h16m25s701616us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8568_1/results_fft_Fill8568_1_117.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8568_1/117/tree_maker.log
