# This is a HTCondor submission file
error  = error.txt
output = output.txt
log  = log.txt
transfer_output_files=config.yaml
+JobFlavour  = "tomorrow"
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/001
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/001/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/002
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/002/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/004
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/004/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/005
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/005/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/006
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/006/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/007
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/007/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/008
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/008/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/009
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/009/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/010
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/010/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/011
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/011/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/012
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/012/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/014
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/014/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/015
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/015/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/016
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/016/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/019
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/019/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/021
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/021/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/022
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/022/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/025
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/025/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/026
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/026/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/028
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/028/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/029
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/029/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/030
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/030/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/037
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/037/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/039
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/039/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/040
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/040/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/042
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/042/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/043
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/043/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/053
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/053/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/054
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/054/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/056
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/056/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/057
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/057/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/058
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/058/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/059
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/059/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/060
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/060/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/061
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/061/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/062
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/062/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/063
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/063/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/064
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/064/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/065
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/065/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/066
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/066/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/068
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/068/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/069
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/069/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/070
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/070/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/071
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/071/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/072
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/072/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/074
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/074/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/076
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/076/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/078
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/078/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/080
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/080/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/082
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/082/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/084
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/084/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/087
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/087/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/090
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/090/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/093
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/093/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/094
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/094/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/096
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/096/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/097
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/097/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/098
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/098/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/099
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/099/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/100
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/100/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/106
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/106/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/107
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/107/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/108
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/108/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/109
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/109/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/110
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/110/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/112
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/112/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/113
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/113/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/114
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/114/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/120
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/120/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/121
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/121/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/123
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/123/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/126
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/126/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/127
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/127/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/128
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/128/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/133
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/133/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/134
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/134/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/147
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/147/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/150
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/150/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/151
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/151/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/152
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/152/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/155
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/155/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/156
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/156/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/157
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/157/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/164
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/164/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/165
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/165/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/166
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/166/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/168
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/168/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/169
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/169/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/173
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/173/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/174
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/174/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/176
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/176/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/177
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/177/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/179
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/179/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/183
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/183/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/184
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/184/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/186
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/186/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/189
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/189/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/190
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/190/run.sh
queue
initialdir = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/191
executable = /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/004_nxcals_htcondor/ADT_2022_2/191/run.sh
queue
#htc
