adt_file:
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_14h40m45s279499us.h5
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_14h41m43s557139us.h5
bunch_nb_b1:
- 1067
- 1114
- 2008
- 2855
- 2902
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8469_5/results_fft_Fill8469_5_005.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor/Fill8469_5/005/tree_maker.log
