adt_file:
- ADTObsBox_data/B1H_Q7/31/5/B1H_Q7_20230331_05h19m55s626574us.h5
- ADTObsBox_data/B1H_Q7/31/5/B1H_Q7_20230331_05h20m53s904201us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8515_1/results_fft_Fill8515_1_008.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8515_1/008/tree_maker.log
