adt_file:
- ADTObsBox_data/B1H_Q7/10/18/B1H_Q7_20230410_18h13m29s243172us.h5
- ADTObsBox_data/B1H_Q7/10/18/B1H_Q7_20230410_18h14m27s520694us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8568_1/results_fft_Fill8568_1_086.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8568_1/086/tree_maker.log
