adt_file:
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h12m42s613673us.h5
- /eos/project/l/lhc-lumimod/MD7003/ADTObsBox/data_Fill8469/B1H_Q7_20221123_15h13m46s718950us.h5
bunch_nb_b1:
- 1114
- 2008
- 2902
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8469_3/results_fft_Fill8469_3_021.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor/Fill8469_3/021/tree_maker.log
