adt_file:
- ADTObsBox_data/B1H_Q7/31/3/B1H_Q7_20230331_03h03m33s448722us.h5
- ADTObsBox_data/B1H_Q7/31/3/B1H_Q7_20230331_03h04m37s554128us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8514_1/results_fft_Fill8514_1_021.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8514_1/021/tree_maker.log
