adt_file:
- ADTObsBox_data/B1H_Q7/31/4/B1H_Q7_20230331_04h21m33s137814us.h5
- ADTObsBox_data/B1H_Q7/31/4/B1H_Q7_20230331_04h22m37s243101us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8514_1/results_fft_Fill8514_1_060.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8514_1/060/tree_maker.log
