adt_file:
- ADTObsBox_data/B1H_Q7/30/14/B1H_Q7_20230330_14h21m05s467767us.h5
- ADTObsBox_data/B1H_Q7/30/14/B1H_Q7_20230330_14h22m03s745419us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8510_1/results_fft_Fill8510_1_011.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8510_1/011/tree_maker.log
