adt_file:
- ADTObsBox_data/B1H_Q7/30/14/B1H_Q7_20230330_14h25m04s406145us.h5
- ADTObsBox_data/B1H_Q7/30/14/B1H_Q7_20230330_14h26m02s683800us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8510_1/results_fft_Fill8510_1_013.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8510_1/013/tree_maker.log
