adt_file:
- ADTObsBox_data/B1H_Q7/30/11/B1H_Q7_20230330_11h05m45s793315us.h5
- ADTObsBox_data/B1H_Q7/30/11/B1H_Q7_20230330_11h06m44s70825us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8508_1/results_fft_Fill8508_1_046.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8508_1/046/tree_maker.log
