adt_file:
- ADTObsBox_data/B1H_Q7/29/14/B1H_Q7_20230329_14h09m06s170508us.h5
- ADTObsBox_data/B1H_Q7/29/14/B1H_Q7_20230329_14h10m04s448160us.h5
bunch_nb_b1:
- all
bunch_nb_b2:
- all
save_to: /eos/user/a/aradosla/FFTs/Fill8503_1/results_fft_Fill8503_1_002.parquet
log_file: /afs/cern.ch/work/a/aradosla/private/ADTObsBox_analysis/002_submit_analysis_htcondor_live/Fill8503_1/002/tree_maker.log
